version: '3'

services:
 mysql:
  image:mysql: 5.7
  restart: always
  enviroment: 
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: cobranca
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   ports:
    - "3306:3306"
  volumes:
    "/home/guilherme/desenvolvimento/volumes/mysql:/var/lib/mysql"

